- hosts: all
  become: yes
  tasks:
   - name: install Docker
     yum:
       name: docker
       state: present
       update_cache: true

   - name: Add repository
     yum_repository:
       name: kubernetes
       description: kubernetes repository
       baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
       gpgcheck: no

   - name: install kubelet
     yum:
       name: kubelet
       state: present
       update_cache: true

   - name: install kubeadm
     yum:
       name: kubeadm
       state: present

- hosts: masters
  become: yes
  tasks:
   - name: install kubectl
     yum:
       name: kubectl
       state: present
       force: yes

