apiVersion: v1
kind: Service
metadata:
  name: syam-java
spec:
  selector:
    app: java
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9376
  clusterIP: 10.0.171.10
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.10
